# Generated by Django 4.2.11 on 2024-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aplicacao', models.CharField(max_length=50)),
                ('comando', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
            ],
        ),
    ]
