# Generated by Django 5.0.4 on 2024-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medicao', models.CharField(max_length=30)),
                ('medicao_atual', models.FloatField(blank=True)),
            ],
        ),
    ]
