# Generated by Django 4.2.11 on 2024-04-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medicao', models.CharField(max_length=30)),
                ('medicao_atual', models.FloatField(blank=True, null=True)),
                ('esta_ativo', models.BooleanField(default=False)),
                ('porta', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
