# Generated by Django 5.0.4 on 2024-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='medicao_atual',
            field=models.FloatField(null=True),
        ),
    ]
