# Generated by Django 5.0.4 on 2024-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicao', models.CharField(max_length=30)),
                ('temp_atual', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataConnection',
        ),
    ]
