# Generated by Django 5.0.4 on 2024-04-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dispositivo_medicao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='esta_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
